import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Share_Tech } from 'next/font/google';


const shareTech = Share_Tech({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-share-tech",
  display: "swap",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} ${shareTech.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}

